# Generated by Django 3.2 on 2021-12-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
