# Generated by Django 3.2 on 2021-12-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0049_auto_20211211_1145'),
        ('SAAS', '0017_auto_20211211_1145'),
        ('adminpanel', '0003_contact_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.countrymodel'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAAS.shop'),
        ),
    ]
