# Generated by Django 3.2 on 2021-12-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0049_auto_20211211_1145'),
        ('SAAS', '0017_auto_20211211_1145'),
        ('pharmacy', '0002_medicinecartitems_medicinecheckout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='med_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicinebrand'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='med_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicinecategory'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='med_power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicinepower'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='med_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.vendor'),
        ),
        migrations.AlterField(
            model_name='medicinebrand',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAAS.shop'),
        ),
        migrations.AlterField(
            model_name='medicinecartitems',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicine'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAAS.shop'),
        ),
        migrations.AlterField(
            model_name='medicinecheckout',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAAS.shop'),
        ),
    ]
