# Generated by Django 3.2 on 2021-12-11 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SAAS', '0016_packagecheckout_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagecheckout',
            name='customer_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packagecheckout',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAAS.package'),
        ),
        migrations.AlterField(
            model_name='packagecheckout',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAAS.shop'),
        ),
    ]
