# Generated by Django 3.2 on 2021-12-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0016_packagecheckout_is_expired'),
        ('restaurant', '0041_refundmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundmodel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAAS.shop'),
        ),
    ]
