# Generated by Django 3.2 on 2021-12-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0044_brand_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='trade_license',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
