# Generated by Django 3.2 on 2021-12-11 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0016_packagecheckout_is_expired'),
        ('restaurant', '0047_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.citymodel'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.countrymodel'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAAS.shop'),
        ),
    ]
