# Generated by Django 3.2 on 2021-12-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0017_auto_20211211_1145'),
        ('restaurant', '0049_auto_20211211_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='duemodel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAAS.shop'),
        ),
    ]
