# Generated by Django 3.2 on 2021-12-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0051_duemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='duemodel',
            name='due_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
