# Generated by Django 3.2 on 2021-12-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0052_duemodel_due_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duemodel',
            old_name='due_complete',
            new_name='due_clear',
        ),
    ]
