# Generated by Django 3.2 on 2021-12-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0053_rename_due_complete_duemodel_due_clear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecheckout',
            name='table_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], max_length=255, null=True),
        ),
    ]
